export default Data = [
    {id: 1, text: 'Item One', color: 'red'},
    {id: 2, text: 'Item Two', color: 'blue'},
    {id: 3, text: 'Item Three', color: 'yellow'},
    {id: 4, text: 'Item Four', color: 'green'},
    {id: 5, text: 'Item Five', color: 'orange'},
    {id: 6, text: 'Item Six', color: 'red'},
    {id: 7, text: 'Item Seven', color: 'blue'},
    {id: 8, text: 'Item Eight', color: 'yellow'},
    {id: 9, text: 'Item Nine', color: 'green'},
    {id: 10, text: 'Item Ten', color: 'orange'},
    {id: 11, text: 'Item Eleven', color: 'red'},
    {id: 12, text: 'Item Twelve', color: 'blue'},
    {id: 13, text: 'Item Thirteen', color: 'yellow'},
    {id: 14, text: 'Item Fourteen', color: 'green'},
    {id: 15, text: 'Item Fifteen', color: 'orange'},
] 